### ISSUE TITLE
Add ssh-copy-id wrapper

### ISSUE THREAD

**Issue by brenns10** [oracle/yo#16]

**Comment by AnuravModak** [comment]
can u assign this me, I have recently joined Oracle and under training this might help to gain some hands-on experience, any reference or description or any lead could be helpful to understand and resolve it. @brenns10

**Comment by brenns10** [comment]
Hi @AnuravModak, sure. Feel free to reach out to me directly on Slack as well.

The purpose of the command, which should be called `yo copy-id`, would be to copy an SSH public key onto an instance using ssh-copy-id. Since Yo assumes you can SSH into the instance already, you'll need to specify whichever key you want to copy on via file. For example, suppose you have `~/.ssh/id_foo` and `~/.ssh/id_bar`, and the instance already has your key for `foo` on there, then the user would do something like this:
```
yo copy-id instance-name -i ~/.ssh/id_bar.pub
```
That command should add the public key to the instance's `~/.ssh/authorized_keys` file. You would essentially pass through the `-i` value, and if it's not provided, the default behavior of SSH would be to copy all keys.

You can take a look at each of the commands in `yo/main.py` to see how they're implemented. You'd probably want to inherit from `SingleInstanceCommand`. And then you're just calling `ssh-copy-id` with the right arguments via subprocess.

**Comment by AnuravModak** [comment]
Thanks for assigning me, Sadly, I am unable to connect to you on slack as it is asking me to contact admin. I hope we can carry forward the discussion here. 
After scrutinizing the repo for the last 10+ hrs , especially "yo/main.py" as you have mentioned. I read and analyzed how different things were included and implemented and constructed. From my limited learning I have constructed the code below :

**CODE : (changes that has to be made in "yo/main.py")**

class copyIdCmd(SingleInstanceCommand):
    name="copy-id"
    description="copy an SSH public key onto an instance using ssh-copy-id"

    def add_args(self, parser: argparse.ArgumentParser) -> None:
        parser.add_argument("instance_name",type=str, help="Name of the instance")
        parser.add_argument("-i","--identity-file",type=str, required=True, help="Specify path to the public key file")

    def run(self) -> None:
        #Firstly, we need to extract instance name and public key file path from command-line arguments
        instance_name=self.args.instance_name
        public_key_file_path=self.args.identity_file

        # Extracting the instance using the name
        instance = self.c.get_instance_by_name(instance_name)

        # Checking if instance exists before moving forward
        if instance is None:
            self.c.con.print(f"Instance '{instance_name}' not found.")
            return

        #Now, construct the command as instance exists
        ssh_copy_id_cmd=[
            "ssh-copy-id",
            "-i",
            public_key_file_path,
            f"{instance.name}@{instance.ip}"
        ]

        #Execution starts
        try:
            subprocess.run(ssh_copy_id_cmd,check=True)
            self.c.con.print(f"SSH public key copied to '{instance.name}' successfully.")
        except Exception as e:
            self.c.con.print(f"Error copying SSH public key: {e}")
        # currently not sure which error to catch most probably "subprocess.CalledProcessError"

** I am quite doubtful how to implement it in main(), maybe I need help here.......**
def main() -> None:
        .
        .
        .

        # Add the CopyIdCmd command
        parser.add_argument(
            "copy-id",
            action=copyIdCmd, 
            help="Copy SSH public key to an instance",
        )

        .
        .
        .
        ...........

Please let me know the further changes i need to do from my side
I hope, I was able to reach nearby your idea of resolving this issue.

**Comment by brenns10** [comment]
(I updated your comment a bit to improve the formatting, you probably wanted to use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks))

First, please provide code changes in a pull request. It's totally fine to share a very rough draft as a pull request and ask for feedback - just say so in the description. It's much easier to review code in the PR interface from Github rather than seeing it copy/pasted into an issue.

Second, to answer your question about `main()`, there's no code change required. Simply defining a subclass of `SingleInstanceCommand` is enough to add the command to Yo. This is a bit of magic that is courtesy of the "subc" sub-command library Yo uses. Essentially, any leaf class that inherits from the base class (in this case, YoCmd), gets added to the main CLI. Feel free to just try it and see :)

Third, here are a suggestions from what I see:

1. Please call it `CopyIdCmd` (upper case first letter). This matches the rest of the class names.
2. Take a look at the other classes which inherit from `SingleInstanceCommand` - you'll notice that they don't define a `run()` method, they define `run_for_instance(self, instance: YoInstance)`. The `SingleInstance` command takes care of adding the proper command line argument and looking up the instance by name. All you need to do is the actual logic.
3. The actual logic looks good. I would prefer you catch `subprocess.CalledProcessError` rather than `Exception`. You "expect" that the command might fail, but `Exception` would catch other errors that might be due to bugs in Yo.

**Comment by AnuravModak** [comment]
Firstly sorry for the rookie mistakes I have committed, I will keep those things in mind.
And, I made some changes and extended the same through a pull request. 
Kindly review it and let me know.

**Comment by brenns10** [comment]
Closed in #20
